#!/bin/sh
[ "$ACTION" = ifup ] || exit 0
sleep 6
netok=$(ping 192.168.88.254 -c3 |grep "time=")
if [ "$netok" ]; then
   return
else
   killall netclient ; sleep 5 && killall netclient ; sleep 5 && (netclient daemon &)
fi
